### ISSUE TITLE
The tsbin command's shebang ends with a carriage return

### ISSUE THREAD

**Issue by ghost** [joaompneves/tsviz#17]
This causes the following error on Linux systems when executing tsviz:

/usr/bin/env: ‘node\r’: No such file or directory

This can be worked around by running the following after installing tsviz (you may need to install the dos2unix program):

dos2unix -F `which tsviz`

Edit: backtick escapes

**Comment by joaompneves** [comment]
Working OK on my OSX. File is LF not CRLF.
Can you check with the latest version if the problem still exists?
