### ISSUE TITLE
No diagram generated

### ISSUE THREAD

**Issue by fr31b3u73r** [joaompneves/tsviz#18]
Hi there!
I´m trying to get a UML diagram from my existing Angular 2 (Typescript) project. Sourcecode is located under `src` with some subfolders and an index.ts in it. When I try to run

> tsviz -dependencies src/ C:\Users\xxx\Desktop\test.png

I get "done" from terminal - but that´s it. No .png-file is generated.
Am I missing something using tsviz? Readme is quite short so I couldn´t point out what I did wrong.
If you need any more information I´ll provide you.
Thanks!

**Comment by joaompneves** [comment]
Can you check with the latest version if the problem still persists. I've added a console message to log the number of modules found.

**Comment by fr31b3u73r** [comment]
Thank you for answering!
Using the new version I get 

> Found 0 module(s)

So problem seems to be tsviz does not recognize my (implicit) modules. When making my modules explicit using the `module` keyword tsviz works fine. Perhaps you can add this to readme in order to avoid misunderstanding.
