### ISSUE TITLE
Allow private and static methods and properties

### ISSUE THREAD

**Issue by pitjow** [joaompneves/tsviz#6]
Hi

Currently there are only private signatures allowed. See uml-builder.ts

`function combineSignatures<T extends Element>(elements: T[], map: (e: T) => string): string {
    return elements.filter(e => (e.visibility == Visibility.Public))
        .map(e => map(e) + "\\l")
        .join("");
}`

Here as well private and static methods/prpoerties should be filtered.

What is the reason for only selecting publics?

**Comment by joaompneves** [comment]
The idea behind this project is to show public contracts that's why I'm skipping private stuff.
