### ISSUE TITLE
Allow PopertyDeclarations

### ISSUE THREAD

**Issue by pitjow** [joaompneves/tsviz#7]
In ts-analyser.ts  only GetAccessor and SetAccessor are selected in the case switcher of the analyseNode function. Additionally general PropertyDeclaration should be allowed, otherwiese normal "fields" will never appear in the uml. I used this:

```
case ts.SyntaxKind.PropertyDeclaration:
case ts.SyntaxKind.GetAccessor:
case ts.SyntaxKind.SetAccessor:
```

**Comment by joaompneves** [comment]
It's now supported, check latest version.
